spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\Users\Jedrzej\Documents\coding\todo-app\todo-db'
  jpa:
    hibernate:
      ddl-auto: validate
debug: true